OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-4.1-mini"
